"""Builds docs/vault/README.md — the landing page for the vault study."""

from __future__ import annotations

from pathlib import Path

from vault import vault as V


def build_index(out_dir: Path) -> Path:
    md_path = out_dir / "README.md"
    md_path.write_text(f"""# Vault Door Mechanism Study

This section extends the PyCon 2026 gear-ratio project into a vault-door
mechanism study.

The original gear card explores **reduction**: one input rotation becomes
a much slower output rotation. The vault door study explores
**coordination**: one input rotation moves many locking pins around a
circular door.

The model is inspired by miniature vault-door builds, but it is not an
official model or a replica of any specific design. It is an educational
CAD and geometry project about symmetry, gearing, pin motion, and
parametric design.

> Prime numbers aren't impossible in CAD. They're just rude to symmetry.

## The default door (all numbers live in [`vault.py`](../../src/vault/vault.py))

* Door diameter: **{V.DOOR_DIAMETER_MM:g} mm**, thickness **{V.DOOR_THICKNESS_MM:g} mm**
* Pin count: **{V.PIN_COUNT}**, on a pitch circle of radius **{V.PIN_RADIUS_MM:g} mm**
* Pin travel: **{V.PIN_TRAVEL_MM:g} mm** radial
* Central cam rotation: **{V.CAM_ROTATION_DEG:g}°** (sweeps **{V.ARC_AT_10DEG_MM:.2f} mm** of arc at the pin radius)

Change a number in [`vault.py`](../../src/vault/vault.py) and every page
below re-derives on the next `uv run vault build`.

## The four sections

### 1. [Symmetry — why circles love friendly numbers](symmetry.md)

The angle-step table for {V.PIN_COUNT}, {V.FRIENDLY_PIN_COUNT}, and
their friends. Why a clock-face layout reads as obvious. How opposing
pairs collapse N pins into N/2 mirrored parts.

### 2. [The {V.PRIME_PIN_COUNT}-pin problem](thirteen-pin-problem.md)

A {V.PRIME_PIN_COUNT}-pin layout is mathematically clean and mechanically
awkward. Where the orphan pin lands, why no shared rack works, and what
you give up by picking a prime.

### 3. [Pin counts — comparing {", ".join(str(n) for n in V.COMPARED_PIN_COUNTS)}](pin-counts.md)

A small-multiples grid. Divisor chips. The mechanical case for composite
counts, in one image.

### 4. [Motion and travel — what {V.CAM_ROTATION_DEG:g}° gets you](motion-and-travel.md)

`arc = r·θ`, the cam-radius table, and the careful distinction between
*arc travel* and *radial pin travel*.

### 5. [Onshape workflow](onshape-workflow.md)

How the Python parameters in [`vault.py`](../../src/vault/vault.py) map to
Onshape variables, and a phased plan for building the parametric CAD
model alongside the SVG study.

## Generated, like the explainers

Every SVG and table on these pages is produced by a Python script in
[`src/vault/`](../../src/vault). The maths and visuals come from one
parameter file ([`vault.py`](../../src/vault/vault.py)). CI rebuilds the
pages on every push that touches `src/vault/` and auto-commits the
regenerated markdown + SVGs.

```
src/vault/<topic>.py  ─►  uv run vault build <topic>  ─►  docs/vault/<topic>.md (+ assets/*.svg)
```

## Disclaimer

This is a fan-made educational mechanism study inspired by public maker
videos and general vault-door mechanisms. It is not an official Tested
project and does not reproduce any private plans. Code is MIT; diagrams
and any 3D files released under this directory are CC BY-SA 4.0
([see the repo licenses](../../LICENSE)).

---

*Generated by `src/vault/index.py`.*
""")
    return md_path
