"""How a small cam rotation produces meaningful arc travel."""

from __future__ import annotations

from math import radians
from pathlib import Path

from vault import vault as V
from vault.svg_draw import draw_cam_rotation

SLUG = "motion-and-travel"


def _arc(radius_mm: float) -> float:
    return radius_mm * radians(V.CAM_ROTATION_DEG)


def build(out_dir: Path) -> Path:
    assets = out_dir / "assets"
    assets.mkdir(parents=True, exist_ok=True)

    cam = draw_cam_rotation(V.PIN_RADIUS_MM, V.CAM_ROTATION_DEG,
                            assets / f"{SLUG}-cam{int(V.CAM_ROTATION_DEG)}deg.svg")

    samples = [20, 40, 60, V.PIN_RADIUS_MM, 100]
    table_rows = "\n".join(
        f"| {r:>6.1f} mm | {_arc(r):>6.2f} mm |"
        for r in samples
    )

    md_path = out_dir / f"{SLUG}.md"
    md_path.write_text(f"""# Motion and travel — what {V.CAM_ROTATION_DEG:g}° gets you

A {V.CAM_ROTATION_DEG:g}° rotation doesn't sound like much. At a large
radius, the edge of the mechanism still moves several millimetres — and a
cam slot or linkage can convert some of that motion into useful radial
*pin* travel.

![{V.CAM_ROTATION_DEG:g}° cam sweep at r = {V.PIN_RADIUS_MM:g} mm](assets/{cam.name})

## arc = r · θ

For an angle θ in radians, a point at radius r sweeps an arc of length
r·θ.

```
arc_length = radius × angle_in_radians
{V.CAM_ROTATION_DEG:g}°  =  {radians(V.CAM_ROTATION_DEG):.6f} rad
```

| Radius     | Arc travel at {V.CAM_ROTATION_DEG:g}° |
|-----------:|--------------------------------------:|
{table_rows}

At the default pin radius of {V.PIN_RADIUS_MM:g} mm, a
{V.CAM_ROTATION_DEG:g}° cam rotation sweeps
**{V.ARC_AT_10DEG_MM:.2f} mm** along the pin pitch circle.

## Important caveat — arc travel ≠ pin travel

The pin moves *radially* (in toward the hub or out toward the door edge),
not tangentially. Arc travel is what the cam slot has to cover; the
*pin* travel is whatever component of that arc the slot geometry
projects radially.

The actual radial pin travel depends on the actuator:

* **Cam slot in a rotating plate** — slot angle and slot length set the
  radial component.
* **Rack and pinion** — pin moves in a straight line driven by a
  perpendicular gear; ratio is fixed by gear and rack geometry.
* **Crank linkage** — non-linear; faster near 0°, slower near full
  travel.
* **Lever arm** — multiplies or divides cam motion by the lever ratio.
* **Follower geometry, friction, clearance** — every real mechanism
  gives back some travel to slop and to part finish.

For the default vault parameters (pin travel = {V.PIN_TRAVEL_MM:g} mm),
the actuator must convert ~{V.ARC_AT_10DEG_MM:.1f} mm of arc into
{V.PIN_TRAVEL_MM:g} mm of radial throw. A {V.PIN_TRAVEL_MM:g}/{V.ARC_AT_10DEG_MM:.1f}
≈ {V.PIN_TRAVEL_MM / V.ARC_AT_10DEG_MM:.2f} ratio is well inside what a
short cam slot or a 1:1 lever can handle.

---

*Generated by `src/vault/motion.py`. Cam rotation and pin radius come
from `src/vault/vault.py`.*
""")
    return md_path
