"""Documenting the parametric Onshape workflow that backs the SVG study."""

from __future__ import annotations

from pathlib import Path

from vault import vault as V

SLUG = "onshape-workflow"


def build(out_dir: Path) -> Path:
    assets = out_dir / "assets"
    assets.mkdir(parents=True, exist_ok=True)

    # No SVG required for this page — it's all prose + a table. We still
    # touch the assets dir so the build is consistent.
    md_path = out_dir / f"{SLUG}.md"
    md_path.write_text(f"""# Onshape workflow — making the SVGs match a real CAD model

The diagrams in this section are generated from Python so they always
match the parameters in [`src/vault/vault.py`](../../src/vault/vault.py).
For the *physical* mechanism, the same parameters drive an Onshape
parametric model. This page documents the convention so the two stay in
sync.

## Variables (Onshape ⟷ vault.py)

Define these as Onshape *variables* in the top-level Part Studio. The
column on the right is the matching constant in `vault.py`.

| Onshape variable    | Default        | `vault.py` constant       |
|---------------------|---------------:|---------------------------|
| `#door_diameter`    | {V.DOOR_DIAMETER_MM:g} mm  | `DOOR_DIAMETER_MM`        |
| `#door_thickness`   | {V.DOOR_THICKNESS_MM:g} mm    | `DOOR_THICKNESS_MM`       |
| `#pin_count`        | {V.PIN_COUNT}              | `PIN_COUNT`               |
| `#pin_diameter`     | {V.PIN_DIAMETER_MM:g} mm     | `PIN_DIAMETER_MM`         |
| `#pin_length`       | {V.PIN_LENGTH_MM:g} mm    | `PIN_LENGTH_MM`           |
| `#pin_travel`       | {V.PIN_TRAVEL_MM:g} mm     | `PIN_TRAVEL_MM`           |
| `#pin_radius`       | {V.PIN_RADIUS_MM:g} mm    | `PIN_RADIUS_MM`           |
| `#hub_diameter`     | {V.HUB_DIAMETER_MM:g} mm    | `HUB_DIAMETER_MM`         |
| `#wheel_diameter`   | {V.WHEEL_DIAMETER_MM:g} mm    | `WHEEL_DIAMETER_MM`       |
| `#cam_rotation`     | {V.CAM_ROTATION_DEG:g} deg    | `CAM_ROTATION_DEG`        |
| `#clearance`        | {V.CLEARANCE_MM:g} mm     | `CLEARANCE_MM`            |
| `#plate_thickness`  | {V.PLATE_THICKNESS_MM:g} mm     | `PLATE_THICKNESS_MM`      |

## Suggested phasing

The model is a study, not a product, so it's worth building it in
discardable phases.

### Phase 1 — Static layout
* Circular door slab driven by `#door_diameter` and `#door_thickness`.
* Pin holes via a circular pattern of `#pin_count` instances at
  `#pin_radius`.
* Central hub at `#hub_diameter`.

### Phase 2 — Radial pin motion
* Pins as separate parts.
* Slider mates pinning each pin to a radial axis.
* Animate pins between fully-extended and fully-retracted.

### Phase 3 — One actuator concept
Pick *one* of these to model first. The vault SVG study deliberately
stays neutral about which is "right":

1. **Central cam plate with radial slots** — easiest to visualise, hard
   to tune.
2. **Rack-and-pinion** ring — clean linear motion, more parts.
3. **Rotating ring with angled slots** — compact, follows pin centres.
4. **Linkages from a central wheel to each pin** — most parts, easiest to
   reason about per-pin force.

### Phase 4 — Compare {V.PIN_COUNT} vs. {V.PRIME_PIN_COUNT}

Use Onshape *configurations* (or two parallel Part Studios) to keep both
counts in one document:

```
Vault Door · {V.PIN_COUNT} pins
Vault Door · {V.PRIME_PIN_COUNT} pins
Vault Door · {V.FRIENDLY_PIN_COUNT} pins
```

The {V.PRIME_PIN_COUNT}-pin configuration doesn't have to be fully
functional. A static layout study is enough to show the design problems
documented in [the {V.PRIME_PIN_COUNT}-pin problem](thirteen-pin-problem.md).

## Exporting back to this repo

When you have a STEP export you're happy with, drop it next to
`jmcpheron-card.step` and (eventually) wire up a `cardlab`-style
explode pipeline. For now the SVG study and any Onshape screenshots
live side by side under `docs/vault/` — the SVGs answer "what should
the mechanism look like?" and the screenshots answer "does it close?"

---

*Generated by `src/vault/onshape_workflow.py`. Variable defaults come
from `src/vault/vault.py`.*
""")
    return md_path
