"""Why circular mechanisms like 12, 24, and other friendly numbers."""

from __future__ import annotations

from pathlib import Path

from vault import vault as V
from vault.geometry import angle_step
from vault.svg_draw import draw_opposing_pairs, draw_vault_pin_layout

SLUG = "symmetry"


def build(out_dir: Path) -> Path:
    assets = out_dir / "assets"
    assets.mkdir(parents=True, exist_ok=True)

    twelve = draw_vault_pin_layout(V.PIN_COUNT, assets / f"{SLUG}-12pin.svg")
    twentyfour = draw_vault_pin_layout(V.FRIENDLY_PIN_COUNT,
                                       assets / f"{SLUG}-24pin.svg")
    pairs = draw_opposing_pairs(V.PIN_COUNT,
                                assets / f"{SLUG}-opposing-pairs.svg")

    md_path = out_dir / f"{SLUG}.md"
    md_path.write_text(f"""# Symmetry — why circles love friendly numbers

> A vault door has to coordinate many locking pins from one rotation. The
> pin count you pick changes how easy that coordination is to design,
> mirror, repeat, and balance.

![{V.PIN_COUNT} pins evenly spaced around a vault door](assets/{twelve.name})

## 360 ÷ N — the angle-step table

| Pins (N) | 360 / N        | Clean halves? | Clean quarters? | Clock analogy |
|---------:|---------------:|:--------------|:----------------|:--------------|
| 6        | {angle_step(6):.3f}°    | yes           | no              | every 2 hours |
| 8        | {angle_step(8):.3f}°    | yes           | yes             | half-hours, sort of |
| 12       | {angle_step(V.PIN_COUNT):.3f}°   | yes           | yes             | one per hour |
| 13       | {angle_step(V.PRIME_PIN_COUNT):.3f}°    | no            | no              | drifts off |
| 24       | {angle_step(V.FRIENDLY_PIN_COUNT):.3f}°    | yes           | yes             | hours + half-hours |

For N = {V.PIN_COUNT}, every pin sits exactly {angle_step(V.PIN_COUNT):g}° from its
neighbours. Think of it as a clock face — the layout snaps to the same
positions a wall clock uses, which is why a {V.PIN_COUNT}-pin layout reads
as obvious without any extra annotation.

## Opposing pairs

A pin at angle θ and another at angle θ + 180° are an *opposing pair*. A
mechanism that drives both ends of the pair from one shared link only
needs N/2 unique parts, mirrored. That only works if N is even.

![{V.PIN_COUNT} pins resolved into 6 opposing pairs](assets/{pairs.name})

For N = {V.PIN_COUNT} pins, that's 6 pairs. For N = {V.FRIENDLY_PIN_COUNT}
pins, 12 pairs. For N = {V.PRIME_PIN_COUNT}, no exact pairs at all — one
pin always lands without a partner across the diameter. (See [the 13-pin
problem](thirteen-pin-problem.md).)

## Why {V.FRIENDLY_PIN_COUNT} is *especially* flexible

![{V.FRIENDLY_PIN_COUNT} pins evenly spaced — twice the resolution of {V.PIN_COUNT}](assets/{twentyfour.name})

{V.FRIENDLY_PIN_COUNT} divides cleanly by 1, 2, 3, 4, 6, 8, 12, and {V.FRIENDLY_PIN_COUNT}.
That's eight ways to split the layout into mirrored or repeated subassemblies.
The mechanism designer can group pins into halves, quarters, sixths,
eighths — whatever the actuator wants — and still get even spacing.

A {V.FRIENDLY_PIN_COUNT}-pin door is not "twice as locked" as a
{V.PIN_COUNT}-pin door; it just gives you finer rotational resolution and
more ways to share parts.

---

*Generated by `src/vault/symmetry.py`. Edit `src/vault/vault.py` and the
numbers above re-derive on the next build.*
""")
    return md_path
