"""The fun one — 13 pins is mathematically possible, mechanically awkward."""

from __future__ import annotations

from pathlib import Path

from vault import vault as V
from vault.geometry import angle_step, divisors
from vault.svg_draw import (
    draw_13_pin_problem,
    draw_opposing_pairs,
    draw_vault_pin_layout,
)

SLUG = "thirteen-pin-problem"


def build(out_dir: Path) -> Path:
    assets = out_dir / "assets"
    assets.mkdir(parents=True, exist_ok=True)

    layout = draw_vault_pin_layout(V.PRIME_PIN_COUNT,
                                   assets / f"{SLUG}-layout.svg")
    orphan = draw_opposing_pairs(V.PRIME_PIN_COUNT,
                                 assets / f"{SLUG}-orphan.svg")
    side_by_side = draw_13_pin_problem(assets / f"{SLUG}-side-by-side.svg")

    twelve_div = ", ".join(str(x) for x in divisors(V.PIN_COUNT))
    thirteen_div = ", ".join(str(x) for x in divisors(V.PRIME_PIN_COUNT))
    twentyfour_div = ", ".join(str(x) for x in divisors(V.FRIENDLY_PIN_COUNT))

    md_path = out_dir / f"{SLUG}.md"
    md_path.write_text(f"""# The {V.PRIME_PIN_COUNT}-pin vault problem

A {V.PRIME_PIN_COUNT}-pin vault door is not impossible. In CAD, placing
{V.PRIME_PIN_COUNT} equally spaced pins around a circle is one circular
pattern away.

The problem is that mechanisms aren't just math. Physical designs like
*symmetry, repeated parts, mirrored linkages,* and *predictable
clearances*. {V.PRIME_PIN_COUNT} is prime, so it refuses many of the
shortcuts that make a {V.PIN_COUNT}-pin or {V.FRIENDLY_PIN_COUNT}-pin
mechanism elegant.

> Prime numbers aren't impossible in CAD. They're just rude to symmetry.

![{V.PRIME_PIN_COUNT} pins evenly spaced — the math is fine](assets/{layout.name})

## The math works

{V.PRIME_PIN_COUNT} pins can be spaced exactly evenly:

```
360 / {V.PRIME_PIN_COUNT} = {angle_step(V.PRIME_PIN_COUNT)}°
```

Place pin 0 at the top, walk {angle_step(V.PRIME_PIN_COUNT):.3f}° around
the circle for each subsequent pin, and the {V.PRIME_PIN_COUNT}th pin lands
exactly where you started. Geometrically: clean.

## The symmetry doesn't

There are no exact opposite pairs. A pin at angle A doesn't have another
pin exactly 180° away.

![pin 0 highlighted; the would-be-opposite point lands between two real pins](assets/{orphan.name})

That dashed marker is where pin 0's "partner" *would* sit on a
{V.PIN_COUNT}-pin door. On {V.PRIME_PIN_COUNT} pins it falls between two
real pins, off by half an angle step
({angle_step(V.PRIME_PIN_COUNT) / 2:.3f}°).

![side-by-side: {V.PIN_COUNT} pins resolve into 6 chord pairs; {V.PRIME_PIN_COUNT} pins resolve into 1 orphan and zero exact pairs](assets/{side_by_side.name})

## Why that matters

If a design uses any of these shortcuts:

* one shared rack driving two pins on opposite sides
* a single mirrored linkage subassembly used N/2 times
* a cam plate with N/2-fold rotational symmetry
* matched pairs of pins that share an actuator
* balanced forces around the diameter

…then a {V.PRIME_PIN_COUNT}-pin count forces a custom solution for the
unmatched pin (or every pin).

## Divisors, in plain sight

```
divisors({V.PIN_COUNT}) = {twelve_div}
divisors({V.PRIME_PIN_COUNT}) = {thirteen_div}
divisors({V.FRIENDLY_PIN_COUNT}) = {twentyfour_div}
```

Composite numbers give mechanical designers more ways to divide, mirror,
and repeat a design. Prime numbers give fewer shortcuts.

## Not impossible — just less reusable

A {V.PRIME_PIN_COUNT}-pin design *could* work with:

* a cam plate with {V.PRIME_PIN_COUNT} independent follower slots
* {V.PRIME_PIN_COUNT} independent levers driven by individual cam profiles
* a worm-gear ring driving each pin off its own pinion

What it gives up is the elegant repetition of {V.PIN_COUNT} or
{V.FRIENDLY_PIN_COUNT}: shared parts, mirrored subassemblies, predictable
balance.

So: pick {V.PIN_COUNT} or {V.FRIENDLY_PIN_COUNT} unless you want to make
{V.PRIME_PIN_COUNT} interesting on purpose.

---

*Generated by `src/vault/thirteen_pin.py`. Pin counts come from
`src/vault/vault.py`.*
""")
    return md_path
