"""Explainer #5 — decoding the gear card from STEP geometry.

Onshape's STEP export drops parametric metadata (gear ratios, tooth counts,
module). All we get is named B-rep solids. This explainer demonstrates
*recovering* the lost design intent from the bytes:

    1. Slice the committed STL of one gear at two z heights.
    2. For each slice, sample the radial profile r(θ) and FFT it.
    3. The dominant non-DC frequency is the tooth count.
    4. The outer radius + tooth count gives the module via
       ``m = 2·r_outer / (N + 2)``.
    5. Compare derived numbers to the canonical values in ``card.py``.

Then a "rolling measuring tape" thought experiment uses the *derived* ratio
to ask: if you rolled the card on edge like a coin, how does the output
gear behave?

Everything is regenerated by CI on every push that touches the STL or this
file, so the page is always honest about what the bytes actually contain.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path

import drawsvg as dw
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

from explainers import card, diagrams, style as S


mpl.rcParams["svg.hashsalt"] = "explainers"


SLUG = "decoding-gears"

# Repo root resolved from this file's location so the STL path doesn't
# depend on where the build command is run from.
REPO_ROOT = Path(__file__).resolve().parents[2]
GEAR_STL = REPO_ROOT / "docs" / "assets" / "card" / "parts" / "Spur_gear_40_teeth_4.stl"


@dataclass(frozen=True)
class ToothFingerprint:
    z: float                # slice height in mm
    count: int              # detected tooth count (FFT-dominant frequency)
    r_outer: float          # max radial distance in the slice (mm)
    r_inner: float          # min radial distance — useful as sanity check
    derived_module: float   # m = 2·r_outer / (N + 2), in mm
    theta_grid: np.ndarray  # angular samples, shape (720,)
    r_grid: np.ndarray      # radial signal at each theta, shape (720,)
    fft_magnitudes: np.ndarray  # |FFT(r - mean)|, shape (361,)


# ---------------------------------------------------------------------------
# Geometry analysis
# ---------------------------------------------------------------------------

def _slice_r_grid(mesh, z: float, samples: int = 720) -> np.ndarray:
    """Slice ``mesh`` at height ``z`` and return radial-distance-vs-angle.

    Uses trimesh's low-level ``mesh_plane`` (returns ``(N, 2, 3)`` line
    segments) rather than ``mesh.section()`` so we don't need the
    networkx dependency that Path2D pulls in.
    """
    from trimesh.intersections import mesh_plane

    segs = mesh_plane(mesh, plane_normal=[0, 0, 1], plane_origin=[0, 0, z])
    if segs is None or len(segs) == 0:
        raise RuntimeError(f"empty mesh slice at z={z}")

    pts = segs.reshape(-1, 3)
    r = np.hypot(pts[:, 0], pts[:, 1])
    theta = np.arctan2(pts[:, 1], pts[:, 0])

    # Bucket each θ into one of ``samples`` slots and keep the max r in
    # each bucket. A gear cross-section may contain inner features (hub
    # hole, post hole); the outer boundary always has the largest r.
    bucket_size = 2 * np.pi / samples
    bucket_idx = ((theta + np.pi) / bucket_size).astype(int).clip(0, samples - 1)
    r_grid = np.zeros(samples)
    np.maximum.at(r_grid, bucket_idx, r)

    # Fill any empty buckets by interpolation from neighbors.
    mask = r_grid > 0
    if mask.sum() < samples:
        idx = np.arange(samples)
        r_grid = np.interp(idx, idx[mask], r_grid[mask])
    return r_grid


def _tooth_count_via_fft(r_grid: np.ndarray) -> tuple[int, np.ndarray]:
    """Return the dominant angular frequency of r_grid plus the full spectrum.

    A periodic tooth profile produces a strong peak at frequency N (the
    tooth count). DC is bin 0; ignore it. We search up to Nyquist.
    """
    n = len(r_grid)
    signal = r_grid - r_grid.mean()
    spectrum = np.abs(np.fft.rfft(signal))
    # Ignore DC bin; the largest remaining bin index is the tooth count.
    peak_bin = int(np.argmax(spectrum[1:])) + 1
    return peak_bin, spectrum


def _detect(mesh, z: float) -> ToothFingerprint:
    samples = 720
    theta_grid = np.linspace(-np.pi, np.pi, samples, endpoint=False)
    r_grid = _slice_r_grid(mesh, z, samples=samples)
    count, spectrum = _tooth_count_via_fft(r_grid)
    r_outer = float(r_grid.max())
    return ToothFingerprint(
        z=z,
        count=count,
        r_outer=r_outer,
        r_inner=float(r_grid.min()),
        derived_module=2 * r_outer / (count + 2),
        theta_grid=theta_grid,
        r_grid=r_grid,
        fft_magnitudes=spectrum,
    )


# ---------------------------------------------------------------------------
# Diagram generators
# ---------------------------------------------------------------------------

def _section_outlines_svg(
    out: Path, disc: ToothFingerprint, pinion: ToothFingerprint,
) -> Path:
    """Side-by-side drawsvg view of the two cross-sections.

    Both at the same px-per-mm scale so the size difference between the
    25.2 mm disc and the 7.2 mm pinion is honest. Panel width is set
    wide enough to fit the longest caption line at FONT_SIZE_DIM.
    """
    px_per_mm = 5.5
    pad = 28.0
    label_h = 54.0  # room for two label lines + breathing
    # Panel width: max of (disc gear + 2mm padding) and minimum for labels.
    gear_w = 2 * (disc.r_outer + 2) * px_per_mm
    panel_w = max(gear_w, 240.0)
    panel_h = gear_w
    gap = pad
    width = 2 * pad + 2 * panel_w + gap
    height = pad + panel_h + label_h + pad

    d = diagrams.new_drawing(width, height)

    def draw_panel(panel_x: float, fp: ToothFingerprint, title: str,
                   fill: str) -> None:
        cx = panel_x + panel_w / 2
        cy = pad + panel_h / 2
        # Boundary as a polygon: convert (θ, r) to (x, y) in px.
        pts: list[float] = []
        for theta, r in zip(fp.theta_grid, fp.r_grid):
            x = cx + r * math.cos(theta) * px_per_mm
            y = cy - r * math.sin(theta) * px_per_mm
            pts.extend([x, y])
        d.append(dw.Lines(*pts, close=True,
                          fill=fill, stroke=S.INK,
                          stroke_width=S.STROKE_NORMAL))
        # Reference circle at outer radius for scale
        d.append(dw.Circle(cx, cy, fp.r_outer * px_per_mm,
                           fill="none", stroke=S.INK_MUTED,
                           stroke_width=S.STROKE_DIM, stroke_dasharray="2 3"))
        # Origin cross-hairs
        d.append(dw.Line(cx - 6, cy, cx + 6, cy,
                         stroke=S.INK_MUTED, stroke_width=S.STROKE_DIM))
        d.append(dw.Line(cx, cy - 6, cx, cy + 6,
                         stroke=S.INK_MUTED, stroke_width=S.STROKE_DIM))
        # Two-line caption: title on top, derived metrics below.
        d.append(dw.Text(title, S.FONT_SIZE_LABEL,
                         x=cx, y=pad + panel_h + 18,
                         text_anchor="middle",
                         font_family=S.FONT_FAMILY,
                         fill=S.INK, font_weight="bold"))
        d.append(dw.Text(
            f"{fp.count} teeth · ⌀ outer {fp.r_outer * 2:.2f} mm · "
            f"module {fp.derived_module:.3f} mm",
            S.FONT_SIZE_DIM,
            x=cx, y=pad + panel_h + 36,
            text_anchor="middle",
            font_family=S.FONT_FAMILY, fill=S.INK_MUTED))

    draw_panel(pad, disc, f"Big disc — slice at z = {disc.z:.2f} mm",
               S.GEAR_BIG)
    draw_panel(pad + panel_w + gap, pinion,
               f"Pinion — slice at z = {pinion.z:.2f} mm",
               S.GEAR_PINION)
    d.save_svg(str(out))
    return out


def _polar_signal_svg(
    out: Path, disc: ToothFingerprint, pinion: ToothFingerprint,
) -> Path:
    """Cartesian r(θ) plot for both gears, with tooth count annotated."""
    fig, (ax_disc, ax_pin) = plt.subplots(2, 1, figsize=(6.5, 4.4), sharex=True)

    for ax, fp, color, title in (
        (ax_disc, disc, S.GEAR_BIG, f"Big disc — r(θ) has {disc.count} peaks"),
        (ax_pin, pinion, S.GEAR_PINION,
         f"Pinion — r(θ) has {pinion.count} peaks"),
    ):
        theta_deg = np.degrees(fp.theta_grid)
        ax.plot(theta_deg, fp.r_grid, color=color, linewidth=1.0)
        ax.axhline(fp.r_grid.mean(), color=S.INK_MUTED,
                   linestyle="--", linewidth=0.5)
        ax.set_ylabel("r (mm)", fontsize=9)
        ax.set_title(title, fontsize=10)
        ax.grid(color=S.LEVEL_LINE, linestyle="--", linewidth=0.4)
        ax.set_axisbelow(True)

    ax_pin.set_xlabel("θ (degrees around the gear axis)", fontsize=9)
    ax_pin.set_xticks(np.arange(-180, 181, 45))
    fig.tight_layout()
    fig.savefig(out, format="svg", bbox_inches="tight",
                metadata={"Date": None})
    plt.close(fig)
    return out


def _fft_svg(
    out: Path, disc: ToothFingerprint, pinion: ToothFingerprint,
) -> Path:
    """Stem plot of FFT magnitudes; the dominant bin = tooth count."""
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 3.2))

    for ax, fp, color, title in (
        (axes[0], disc, S.GEAR_BIG, "Big disc"),
        (axes[1], pinion, S.GEAR_PINION, "Pinion"),
    ):
        # Drop DC; clip to show the interesting low end.
        spectrum = fp.fft_magnitudes
        max_bin = min(fp.count * 3 + 5, len(spectrum) - 1)
        bins = np.arange(1, max_bin + 1)
        mags = spectrum[1:max_bin + 1]
        markerlines = ax.stem(bins, mags, basefmt=" ")
        plt.setp(markerlines.markerline, color=color, markersize=4)
        plt.setp(markerlines.stemlines, color=color, linewidth=0.8)
        # Highlight the winning bin
        ax.axvline(fp.count, color=S.ACCENT_HILITE, linestyle="--",
                   linewidth=0.8, alpha=0.7)
        ax.annotate(f"N = {fp.count}",
                    xy=(fp.count, mags.max()),
                    xytext=(8, -2), textcoords="offset points",
                    fontsize=10, color=S.ACCENT_HILITE, fontweight="bold")
        ax.set_xlabel("angular frequency (cycles per revolution)", fontsize=8)
        ax.set_ylabel("|FFT(r − mean)|", fontsize=8)
        ax.set_title(title, fontsize=10)
        ax.grid(color=S.LEVEL_LINE, linestyle="--", linewidth=0.4)
        ax.set_axisbelow(True)

    fig.tight_layout()
    fig.savefig(out, format="svg", bbox_inches="tight",
                metadata={"Date": None})
    plt.close(fig)
    return out


def _comparison_svg(
    out: Path, disc: ToothFingerprint, pinion: ToothFingerprint,
) -> Path:
    """Bar chart: canonical (card.py) vs derived (from STL) for 5 params."""
    derived_ratio_per_stage = disc.count / pinion.count
    derived_total_ratio = derived_ratio_per_stage ** (card.N_STAGES - 1)

    labels = [
        "big teeth", "pinion teeth", "module (mm)",
        "ratio/stage", "total ratio",
    ]
    canonical = [
        card.BIG_TEETH, card.PINION_TEETH, card.MODULE_MM,
        card.RATIO_PER_STAGE, card.TOTAL_RATIO,
    ]
    derived = [
        disc.count, pinion.count, disc.derived_module,
        derived_ratio_per_stage, derived_total_ratio,
    ]

    x = np.arange(len(labels))
    width = 0.36

    fig, ax = plt.subplots(figsize=(7.0, 3.4))
    ax.bar(x - width / 2, canonical, width,
           color=S.GEAR_BIG, edgecolor=S.INK, linewidth=0.5,
           label="canonical (card.py)")
    ax.bar(x + width / 2, derived, width,
           color=S.ACCENT_HILITE, edgecolor=S.INK, linewidth=0.5,
           label="derived (from STL)")
    ax.set_yscale("log")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=9)
    ax.set_ylabel("value (log)", fontsize=9)
    ax.set_title("Canonical design vs. geometry-derived values",
                 fontsize=11)
    ax.legend(fontsize=8, loc="upper left")
    ax.grid(axis="y", which="both", color=S.LEVEL_LINE,
            linestyle="--", linewidth=0.4)
    ax.set_axisbelow(True)
    for xi, (c, dv) in enumerate(zip(canonical, derived)):
        for offset, val in ((-width / 2, c), (width / 2, dv)):
            label = f"{val:.3g}" if val < 1000 else f"{val:.0f}"
            ax.text(xi + offset, val, label,
                    ha="center", va="bottom", fontsize=7, color=S.INK)
    fig.tight_layout()
    fig.savefig(out, format="svg", bbox_inches="tight",
                metadata={"Date": None})
    plt.close(fig)
    return out


def _rolling_tape_svg(out: Path, disc: ToothFingerprint,
                      derived_total_ratio: float) -> Path:
    """A 1-metre measuring tape with input/output gear position markers."""
    width_mm = 1000.0  # we map 1 m of tape to the page
    px_per_mm = 0.62   # → ~620 px tape
    tape_h = 26.0
    pad = 50.0
    label_h = 90.0
    width = 2 * pad + width_mm * px_per_mm
    height = pad + label_h + tape_h + 90 + pad

    d = diagrams.new_drawing(width, height)

    tape_x = pad
    tape_y = pad + label_h
    tape_w = width_mm * px_per_mm

    # Header text
    d.append(dw.Text(
        "Roll the card on edge like a coin — the input gear contacts the floor.",
        S.FONT_SIZE_LABEL, x=width / 2, y=pad + 12,
        text_anchor="middle", font_family=S.FONT_FAMILY,
        fill=S.INK, font_weight="bold"))
    d.append(dw.Text(
        f"Input OD = {disc.r_outer * 2:.2f} mm  ·  "
        f"circumference = {math.pi * disc.r_outer * 2:.1f} mm  ·  "
        f"chain ratio = {int(derived_total_ratio):,}:1",
        S.FONT_SIZE_DIM, x=width / 2, y=pad + 30,
        text_anchor="middle", font_family=S.FONT_FAMILY,
        fill=S.INK_MUTED))

    # Tape body
    d.append(dw.Rectangle(tape_x, tape_y, tape_w, tape_h,
                          fill="#fde68a", stroke=S.INK,
                          stroke_width=S.STROKE_NORMAL))
    # Tick marks every 100 mm, labels every 100 mm
    for mm in range(0, 1001, 50):
        x = tape_x + mm * px_per_mm
        h = 10 if mm % 100 == 0 else 5
        d.append(dw.Line(x, tape_y, x, tape_y + h,
                         stroke=S.INK, stroke_width=S.STROKE_THIN))
        if mm % 200 == 0:
            d.append(dw.Text(f"{mm / 1000:g} m", S.FONT_SIZE_DIM,
                             x=x, y=tape_y + tape_h + 14,
                             text_anchor="middle",
                             font_family=S.FONT_FAMILY, fill=S.INK))

    # Input rotations marker — happens often; show every 5th rotation as a tick
    circumference_mm = math.pi * disc.r_outer * 2
    n_input_rot = width_mm / circumference_mm
    label_y = tape_y - 12
    d.append(dw.Text(f"input gear: {n_input_rot:.1f} rotations over 1 m",
                     S.FONT_SIZE_DIM, x=tape_x, y=label_y,
                     font_family=S.FONT_FAMILY, fill=S.INK_MUTED))

    # Output progress as a thin overlay bar on the tape
    output_rot = n_input_rot / derived_total_ratio
    output_deg = output_rot * 360
    output_frac = output_rot  # one full output rotation maps to all of tape
    # Display "what fraction of an output rotation has happened" as a wedge.
    wedge_cx = pad + tape_w + 28
    wedge_cy = tape_y + tape_h / 2
    if wedge_cx + 38 > width:
        wedge_cx = width - 42  # safety, shouldn't trigger
    d.append(dw.Circle(wedge_cx, wedge_cy, 32,
                       fill=S.PAPER, stroke=S.INK,
                       stroke_width=S.STROKE_NORMAL))
    # Sector of `output_deg` degrees, starting at 12 o'clock (−90° in SVG).
    rad_a = -math.pi / 2
    rad_b = rad_a + math.radians(output_deg)
    arc_x0 = wedge_cx + 32 * math.cos(rad_a)
    arc_y0 = wedge_cy + 32 * math.sin(rad_a)
    arc_x1 = wedge_cx + 32 * math.cos(rad_b)
    arc_y1 = wedge_cy + 32 * math.sin(rad_b)
    large_arc = 1 if output_deg > 180 else 0
    path = dw.Path(fill=S.ACCENT_HILITE, fill_opacity=0.45,
                   stroke=S.INK, stroke_width=S.STROKE_THIN)
    path.M(wedge_cx, wedge_cy).L(arc_x0, arc_y0)
    path.A(32, 32, 0, large_arc, 1, arc_x1, arc_y1)
    path.L(wedge_cx, wedge_cy).Z()
    d.append(path)

    # Tape footer text
    footer_y = tape_y + tape_h + 38
    d.append(dw.Text(
        f"output gear after rolling 1 m: {output_rot:.4f} rotations "
        f"≈ {output_deg:.1f}°",
        S.FONT_SIZE_LABEL,
        x=width / 2, y=footer_y,
        text_anchor="middle", font_family=S.FONT_FAMILY,
        fill=S.ACCENT_HILITE, font_weight="bold"))
    d.append(dw.Text(
        f"To get one full output rotation you'd have to roll "
        f"{(1.0 / output_rot):.1f} metres.",
        S.FONT_SIZE_DIM, x=width / 2, y=footer_y + 18,
        text_anchor="middle", font_family=S.FONT_FAMILY, fill=S.INK_MUTED))

    d.save_svg(str(out))
    return out


def _rolling_scale_svg(out: Path, disc: ToothFingerprint,
                       derived_total_ratio: float) -> Path:
    """A horizontal scale comparison: how far for ONE output rotation."""
    circumference_mm = math.pi * disc.r_outer * 2
    roll_for_one_output_m = derived_total_ratio * circumference_mm / 1000

    # Familiar landmarks for scale (metres)
    landmarks = [
        ("PyCon booth (3 m)", 3.0, S.INK_MUTED),
        ("badminton court (13.4 m)", 13.4, S.INK_MUTED),
        (f"one output click ({roll_for_one_output_m:.1f} m)",
         roll_for_one_output_m, S.ACCENT_HILITE),
        ("Olympic pool (50 m)", 50.0, S.INK_MUTED),
    ]
    max_m = max(m for _, m, _ in landmarks) * 1.05

    width = 880.0
    pad_l = 60.0
    pad_r = 200.0  # generous right margin so "Olympic pool (50 m)" never clips
    row_h = 30.0
    height = 70 + len(landmarks) * row_h + 40
    d = diagrams.new_drawing(width, height)

    d.append(dw.Text(
        "How far do you have to roll the card for the output gear to click once?",
        S.FONT_SIZE_LABEL, x=width / 2, y=24,
        text_anchor="middle", font_family=S.FONT_FAMILY,
        fill=S.INK, font_weight="bold"))

    bar_x = pad_l
    bar_w = width - pad_l - pad_r
    pad = 50.0  # used below for the x-axis label spacing

    for i, (label, m, color) in enumerate(landmarks):
        y = pad + i * row_h
        # Label on the right of the bar
        bar_len = (m / max_m) * bar_w
        d.append(dw.Rectangle(bar_x, y, bar_len, row_h - 8,
                              fill=color, fill_opacity=0.7,
                              stroke=S.INK, stroke_width=S.STROKE_THIN))
        d.append(dw.Text(
            label, S.FONT_SIZE_DIM,
            x=bar_x + bar_len + 6, y=y + (row_h - 8) / 2 + 3,
            font_family=S.FONT_FAMILY,
            fill=color, font_weight="bold" if "output" in label else "normal"))

    # x-axis tick marks
    axis_y = pad + len(landmarks) * row_h + 4
    d.append(dw.Line(bar_x, axis_y, bar_x + bar_w, axis_y,
                     stroke=S.INK, stroke_width=S.STROKE_THIN))
    for m in (0, 10, 20, 30, 40, 50):
        if m > max_m:
            break
        x = bar_x + (m / max_m) * bar_w
        d.append(dw.Line(x, axis_y, x, axis_y + 4,
                         stroke=S.INK, stroke_width=S.STROKE_THIN))
        d.append(dw.Text(f"{m} m", S.FONT_SIZE_DIM,
                         x=x, y=axis_y + 16,
                         text_anchor="middle",
                         font_family=S.FONT_FAMILY, fill=S.INK_MUTED))

    d.save_svg(str(out))
    return out


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def build(out_dir: Path) -> Path:
    """Render the decoding-gears explainer to <out_dir>/decoding-gears.md."""
    if not GEAR_STL.exists():
        raise FileNotFoundError(
            f"can't decode without the gear STL at {GEAR_STL} — "
            f"run `cardlab explode` first to generate per-part artifacts"
        )

    import trimesh
    mesh = trimesh.load(str(GEAR_STL), force="mesh")

    z_min, z_max = float(mesh.bounds[0][2]), float(mesh.bounds[1][2])
    # Pick z heights that are well inside each feature. The big disc sits
    # at the bottom of the STL (z = -1.27 to ~0). The pinion+hub spans
    # the top (~0 to z_max). The midpoints below are robust across small
    # tessellation drift.
    z_disc = z_min + (z_max - z_min) * 0.05    # ~5% into the part, in the disc
    z_pinion = z_min + (z_max - z_min) * 0.55  # mid-pinion, well above the disc

    disc = _detect(mesh, z_disc)
    pinion = _detect(mesh, z_pinion)

    assets = out_dir / "assets"
    assets.mkdir(parents=True, exist_ok=True)

    section_path = _section_outlines_svg(
        assets / f"{SLUG}-sections.svg", disc, pinion)
    polar_path = _polar_signal_svg(
        assets / f"{SLUG}-polar.svg", disc, pinion)
    fft_path = _fft_svg(
        assets / f"{SLUG}-fft.svg", disc, pinion)
    compare_path = _comparison_svg(
        assets / f"{SLUG}-comparison.svg", disc, pinion)

    derived_ratio_per_stage = disc.count / pinion.count
    derived_total_ratio = derived_ratio_per_stage ** (card.N_STAGES - 1)
    tape_path = _rolling_tape_svg(
        assets / f"{SLUG}-1m-tape.svg", disc, derived_total_ratio)
    scale_path = _rolling_scale_svg(
        assets / f"{SLUG}-scale.svg", disc, derived_total_ratio)

    # Derived numbers for prose
    big_circumference_mm = math.pi * disc.r_outer * 2
    n_input_per_m = 1000.0 / big_circumference_mm
    n_output_per_m = n_input_per_m / derived_total_ratio
    deg_output_per_m = n_output_per_m * 360
    roll_for_one_output_m = derived_total_ratio * big_circumference_mm / 1000

    md = f"""# Decoding the gear card from its bytes

> *[your voice here] one-line hook about pulling design intent out of a STEP that pretends it has none.*

When [Onshape exports a STEP file](card-3d.md), it drops everything that
made the part *parametric*: no gear ratios, no tooth counts, no module,
no mate semantics. What you get is a list of B-rep solids with names like
`Spur gear (40 teeth)` — the only surviving design intent is the
parenthetical, and that's just a string.

This page does the opposite operation: it **recovers** the lost design
intent from the geometry. The numbers below are computed by reading the
committed STL of one gear (`docs/assets/card/parts/Spur_gear_40_teeth_4.stl`),
slicing it at two different heights, and asking each cross-section
"how periodic are you?"

## The fingerprint

A gear's outer boundary, viewed in polar coordinates, is a periodic
signal: the radial distance `r(θ)` rises to a tooth tip then falls to a
tooth valley, repeating every `360°/N`. The dominant frequency of that
signal is the tooth count.

![gear cross-sections at two heights](assets/{section_path.name})

The left panel is a horizontal slice of the part **at z = {disc.z:.2f} mm**
— inside the big disc. The right panel is the same gear sliced **at
z = {pinion.z:.2f} mm** — inside the pinion that sits on top of the
disc. They're drawn at the same scale, so the size difference is honest.

## The signal

Rendering `r(θ)` as a cartesian plot makes the periodicity obvious — you
can count the peaks by eye:

![r(theta) for both gears](assets/{polar_path.name})

But we don't need to count by eye. The FFT of `r − mean(r)` puts a
single tall stem at the dominant frequency:

![FFT spectrum of both signals](assets/{fft_path.name})

The dominant bin is the tooth count. For the disc: **{disc.count}
teeth.** For the pinion: **{pinion.count} teeth.** Onshape's part name was
truthful — and now we've verified it without trusting it.

## Recovering the module

A standard gear's outer diameter is `(N + 2) · module`. With both
quantities measured, we can back-solve:

```text
disc:    derived_module = 2 · {disc.r_outer:.3f} / ({disc.count} + 2)
                        = {disc.derived_module:.4f} mm
pinion:  derived_module = 2 · {pinion.r_outer:.3f} / ({pinion.count} + 2)
                        = {pinion.derived_module:.4f} mm
```

Both agree to within rounding. Comparing to the canonical value in
[`card.py`](../../src/explainers/card.py):

![canonical vs derived comparison](assets/{compare_path.name})

The derived ratio per stage is `{disc.count} / {pinion.count}
= {derived_ratio_per_stage:g}`, and for {card.N_STAGES} gears in the chain
(so {card.N_STAGES - 1} meshes), the total ratio is
**{int(derived_total_ratio):,}:1** — matching the canonical
{int(card.TOTAL_RATIO):,}:1.

We have now used Python to recover, from raw mesh data, every parameter
Onshape's STEP exporter threw away.

## The rolling-tape thought experiment

Now that we have a verified ratio, the fun question: **if you rolled the
card on edge along a flat surface — like a coin rolling along a counter —
how does the output gear behave?**

The input gear's outer circumference is
`π · {disc.r_outer * 2:.2f} mm ≈ {big_circumference_mm:.1f} mm`. Rolling
the card one full metre means the input gear makes
`1000 / {big_circumference_mm:.1f} ≈ {n_input_per_m:.2f}` rotations.

Through the {int(derived_total_ratio):,}:1 chain, that becomes:

![1-metre rolling tape](assets/{tape_path.name})

**{n_output_per_m:.4f} rotations.** Or, equivalently:
**{deg_output_per_m:.1f} degrees**. The output gear barely twitches.

Inverting the question: to get **one full output rotation**, you'd have
to roll the card

`{int(derived_total_ratio):,} · {big_circumference_mm:.1f} mm ≈
{roll_for_one_output_m:.1f} metres`

— roughly the length of an Olympic swimming pool, give or take a few
podiums:

![scale comparison](assets/{scale_path.name})

The output gear is a *commitment*. You don't watch it spin; you leave
the room, come back, and check whether it's moved.

## What we used

| Step | Library | Operation |
|---|---|---|
| Load STL | [`trimesh`](https://trimesh.org/) | `trimesh.load(...)` |
| Slice at z | `trimesh.intersections` | `mesh_plane(mesh, ...)` returns segments |
| Bucket to polar grid | `numpy` | `np.maximum.at(r_grid, bucket_idx, r)` |
| Tooth count | `numpy.fft` | dominant bin of `rfft(r − mean(r))` |
| Module back-out | arithmetic | `m = 2·r_outer / (N + 2)` |
| Diagrams | `drawsvg` + `matplotlib` | with `svg.hashsalt` for byte stability |

Zero scipy. Zero hand-tuned thresholds. The FFT does the counting.

## Caveats

- This is a **clean STL** that came from a parametric CAD source. The
  same pipeline run on a scanned-and-meshed gear would need denoising
  and a less idealised peak detector.
- The rolling-tape math assumes pure rolling without slip and lossless
  meshes. The actual printed card will bind from friction and tolerance
  stack-up well before you've rolled 20 metres.
- We sampled exactly one of the gear instances (the tall-hub variant
  at index 4). All five instances are geometrically identical except
  for the hub length, which doesn't affect tooth count or outer
  diameter, so the result generalises.

---

*Generated by [`src/explainers/decoding.py`](../../src/explainers/decoding.py).
Edit the source, not this file.*
"""
    md_path = out_dir / f"{SLUG}.md"
    md_path.write_text(md)
    return md_path
