"""Builds docs/explainers/index.md — the landing page linking all sections."""

from __future__ import annotations

from pathlib import Path

from explainers import card


def build_index(out_dir: Path) -> Path:
    md_path = out_dir / "index.md"
    md_path.write_text(f"""# Engineering writeups for the gear card

> *[your voice here] one paragraph framing the project: a 3D-printed business card with a {int(card.TOTAL_RATIO):,}:1 compound reduction-gear chain, and a Python-driven repo that explains the engineering behind it.*

This directory is a *generated* set of writeups. Every page below is produced by running a Python program in [`src/explainers/`](../../src/explainers). The math, diagrams, and tables come from one canonical parameter file ([`card.py`](../../src/explainers/card.py)) — change a number there and every page reflects it on the next build.

```
src/explainers/<topic>.py  ─►  uv run explainers build <topic>  ─►  docs/explainers/<topic>.md (+ assets/*.svg)
```

## The four sections

### 1. [Gear ratios](gear-ratios.md)

How {card.N_STAGES} compound gears at {card.RATIO_PER_STAGE:g}:1 each compound to {int(card.TOTAL_RATIO):,}:1, and how that translates to your thumb walking metres of arc per output rotation. Bar chart of cumulative ratio per stage; line chart of thumb travel distance.

### 2. [Stacking and interleaving](stacking.md)

The actual engineering puzzle: how do you fit {card.N_STAGES} compound gears in a {card.CARD_THICKNESS_MM:g} mm card without their big discs colliding? Three side-view cross-sections walk through the failure modes and the eventual {card.LEVELS}-level cycle that solves it.

### 3. [Terminology](terminology.md)

Pinion vs big gear, hub vs boss, post vs axle vs arbor. One annotated cross-section labels every named feature; a glossary table covers the rest.

### 4. [3D-printing considerations](printing.md)

Print orientation, the hub-to-pinion overhang and why a 45° chamfer fixes it, and why the post is its own part rather than printed monolithic with the gear.

## Why a Python repo, not a static site?

Each explainer is a deterministic Python program. You can read its source, change a parameter, re-run it, and the writeup updates. The diagrams aren't hand-drawn — they're [SVG primitives](../../src/explainers/diagrams.py) composed by Python from the same canonical inputs. The repo is the explanation.

CI rebuilds these pages on every push that touches [`src/explainers/`](../../src/explainers) and auto-commits the regenerated markdown + SVG, so what you're reading on github.com is always the result of running today's source.

---

*Generated by [`src/explainers/index.py`](../../src/explainers/index.py).*
""")
    return md_path
